### ISSUE TITLE
Empty \k tags are discarded

### ISSUE THREAD

**Issue by ahuei123456** [xIceArcher/lyricsheets#2]
If there's a line that contains a `\k` with no text, it's discarded when the line is imported into the gsheets.

Example [file](https://github.com/xIceArcher/lyricsheets/files/9048601/love.triangle.txt) (first two lines have a blank `\k` that is lost when it's imported.

**Comment by xIceArcher** [comment]
I would say this is expected behavior, allowing an empty string as a syllable text is technically possible but might complicate line termination logic.

You could try to fix it, or simply move the k-tag to cover the whitespace instead for the same effect.

**Comment by xIceArcher** [comment]
I don't foresee that ever happening given that I've timed 150+ songs without that ever happening so will deal with it when it occurs.

**Comment by xIceArcher** [comment]
Resolved.
